apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret #anyname
type: Opaque #default, common but can use TLS certificates also
data:
  mongo-root-username: dXNlcm5hbWU= #base64 encoded username (echo -n "username" | base64)/value (any apropriate name for key)
  mongo-root-password: bXlwYXNzd29yZA== #base64 encoded password/value (any apropriate name for key)